### ISSUE TITLE
[feature request] more logs & delay package updates for X days & prompt user

### ISSUE THREAD

**Issue by bf** [cmuench/pacman-auto-update#26]
Hi @cmuench thanks for this great package, I have been using it for several weeks now. I'm a big fan of this auto-updating approach.

There were several interesting discussions on #archlinux IRC channel about stability of this approach. 

The three main points of criticism by the archlinux IRC community seems to be that installing packages as frequently as once per hour can:

**1) ... make you miss important messages from the packages about urgent manual steps you need to take (e.g. postgresql upgrade)**
**2) ... introduce a new bug and damage your system**
**3) ... choose answers for pacman prompts that you might not want**

If you're open to it, I'd like to find a solution for these two points.

**Potential solution for 1):**
As far as I understand, **1) missing important messages** could be solved by showing some sort of report to the user. Right now, when running `journalctl -u pacman-auto-update -a --no-pager -f` it does not show any messages. Currently the output is like you see below. 

Proposed solution: Maybe we can change this to be more verbose and show the user what has been updated and what the message was?
```
# journalctl -u pacman-auto-update -a --no-pager -f
Mär 14 18:24:33 archibald systemd[1]: pacman-auto-update.service: Consumed 4.708s CPU time.
Mär 14 19:24:59 archibald systemd[1]: Started Pacman Auto Update.
Mär 14 19:25:05 archibald systemd[1]: pacman-auto-update.service: Deactivated successfully.
Mär 15 09:59:25 archibald systemd[1]: Started Pacman Auto Update.
Mär 15 10:00:10 archibald systemd[1]: pacman-auto-update.service: Deactivated successfully.
Mär 15 10:00:10 archibald systemd[1]: pacman-auto-update.service: Consumed 13.432s CPU time.
Mär 15 11:01:40 archibald systemd[1]: Started Pacman Auto Update.
Mär 15 11:01:46 archibald systemd[1]: pacman-auto-update.service: Deactivated successfully.
Mär 15 12:02:25 archibald systemd[1]: Started Pacman Auto Update.
Mär 15 12:02:30 archibald systemd[1]: pacman-auto-update.service: Deactivated successfully.
```

**Potential solution for 2): Auto-Installing buggy packages**
This is both a problem for `pacman-auto-update` and normal pacman users. If you're unlucky, you pull a buggy package as the first person on the planet, and it breaks your system. You open a thread on archlinux forums, the maintainers fix their package, and they release a new version. AFAIK these kind of problems happen around once per month for archlinux. 

Proposed solution: If we adapt auto-update to wait until a package (and it's dependencies) have been in the repos for more than `X`days, then the bug will most likely be resolved by the community and a new package version is released. This allows us to skip the faulty package.

**Potential soltion for 3): Giving wrong answer to pacman prompts**
Maybe it could forward such prompts to the user?

Sorry for the long text.

What do you think about these problems and proposed solutions? Would you be open for a PR?

**Comment by es20490446e** [comment]
> If we adapt auto-update to wait until a package (and it's dependencies) have been in the repos for more than `X`days, then the bug will most likely be resolved by the community and a new package version is released.

You are tapping into a very important aspect, why rolling releases are more bug free compared with fixed release ones.

This is usually counter intuitive, but updating more frequently enhances quality because:

- If there is any issues, it come in a one by one manner. They don't accumulate. You can solve them little by little as soon as the come, versus having a big update that potentially messes up multiple things.

- Fixes will also be brought as soon as possible, automatically. It decreases the window of exposure to bugs, or that the system administrator forgets to upgrade on a critical fix.

- There are already testing repositories in place. People have already received those updates previously.

- I have been using auto-update since February 2021 in all computers I have installed, for my family and my clients, and it never created any extra issue. Which is more reliable than what I expected.


> Maybe we can change this to be more verbose and show the user what has been updated and what the message was?

What auto-update does right now is showing stderr if it fails to upgrade. I chose to do it this way because:

- Messages printed during upgrade are nearly always optional, otherwise they would be automated for sure or they will break the system.

- Those messages are mixed with common upgrade output. You can't easily separate them from the rest. In practice any message usually ends lost unnoticed in a wall of text, specially with recurrent automatic updates.

Maybe showing those messages will be an improvement, but I don't see a meaningful way to implement it. Hence at the time I chose a solution that was just nice enough.

Anyway I'm open to listen for potential options.


> **Giving wrong answer to pacman prompts**
> Maybe it could forward such prompts to the user?

I think one of the main reasons why Linux has never been adopted on the desktop at large is because the overwhelming amount of irrelevant choices an user must make to start using their operating system.

Hence, for mitigating that, I adopted a different philosophy. That there should be a single best choice by default, but the user shall have the option to make a different one when explicitly requested.

My assumption is that 99% of the time those alternatives offered while upgrading don't really make a difference for most people, cause if they did they will just notice and change them.

I think that in the end of the day it all comes down to how much control do you expect to have over your system.

Do you want to make a choice for sure for every little detail, or do you want to make a choice only when you notice an aspect is relevant to you?

I think that for most people is the second one, and for people in the first category they will just avoid any kind of automation all together.

**Comment by bf** [comment]
@es20490446e thanks for your feedback and sorry that I didn't address you right away. 

Thanks also for elaborating your philosophy. I mostly agree but also would love to see the three issues resolved. I was thoroughly grilled and insulted because of my pacman-auto-update questions on #archlinux today so I know how many people conflict with these goals.

However, from your reply I don't see that you are open for PRs or enhancing the project. I will therefore fork it and implement the features. Please let me know if I have an error in my understanding.

Thanks again.

**Comment by es20490446e** [comment]
> I was thoroughly grilled and insulted because of my pacman-auto-update questions on #archlinux today

Because their philosophy is just the opposite: tight manual control over everything.

They will never accept any kind of automation, no matter how you adapt it to their tastes. They are simply not the right people for that, they don't want that to start with.

It's like asking an atheist to become catholic.


> I don't see that you are open for PRs or enhancing the project. I will therefore fork it and implement the features.

I'm very open to improvements. The thing is that in this case I don't see how it could be done without getting into an over-complicated solution.

If you want to try exploring other possibilities, for example by making a fork, that's good.

I think design very deeply, but it doesn't mean my proposal couldn't be improved.

**Comment by es20490446e** [comment]
As I said they don't want any suggestion. It's so that they just removed the package from the AUR: https://github.com/cmuench/pacman-auto-update/issues/27

**Comment by bf** [comment]
Extremely ridiculous. Time for an archlinux for that actually implements auto-updating.

**Comment by es20490446e** [comment]
This is the fourth time they remove a software from me from the AUR.

Someone would think I'm writing malware or something. But it was actually [fonts](https://gitlab.com/es20490446e/express-repository/-/blob/master/recipes/google-fonts/PKGBUILD), a [game](https://gitlab.com/es20490446e/darkmod-linux), and an [tool for managing the AUR](https://gitlab.com/es20490446e/aur-box).

The fonts were removed because they updated monthly instead of daily, which was very inconvenient to update due to the huge size of the package.

The game was removed because it used a middle-ware that allowed to use it by multiple users with each one having their own configs, saves and maps.

Without the middle-ware you would also need to configure user groups manually. And have the game folder editable by everyone, which would allow anyone to supplant the game binaries.

The third plainly because they didn't want a tool for managing the AUR.

The third time this happened I started disagreeing with them, respectfully but unapologetically. As result they banned me on the AUR, and on the forums. After I tried to log in they put a message on the login screen that said "never come back".

With auto-update I guessed that, since the software was started by @cmuench and contributed by @Wurstnase , maybe on this occasion they will leave me alone.

But as you see they won't. I'm starting to suspect this is very personal for them. Probably not with me specifically, it's just that they usually behave like this with anyone else.

I would say that with them there's nothing to fix. They are extremely rude, even sadistic. You simply can't deal with this profile of person.

Happily code never disagrees.

**Comment by bf** [comment]
Hey just wanted to say I feel with you and please don't get demotivated by this. Some members of arch leadership feel this way and it's a decision to argue about.

I'd personally propose to fork pacman into something like `pacwoman` which actually supports signals. Then we build around it a new version of pacman-auto-update which actually forwards the prompts and error messages to the user's GUI (e.g. gnome prototype). 

If they end up deleting `pacwoman` and `pacwoman-auto-update` then nuclear option should be chosen of forking archlinux alltogether and making auto-updates a first-class feature for the OS.

What do you think? Any new developments on this?

**Comment by es20490446e** [comment]
Now autoupdate updates its own package.

For that working you shall reinstall it.
